name: Custom Github Action
description: 'this is a custom github action'
branding:
  icon: check-circle
  color: blue
runs:
  using: "composite"
  steps:
    - name: Main Step
      run: |
        ${{ github.action_path }}/main.ps1
      shell: pwsh
    - name: Run only if workflow is cancelled
      run: |
        ${{ github.action_path }}/cancelJob.ps1
      if: cancelled() || always()
      shell: pwsh
